[package]
name = "sailer"
version = "0.1.0"
edition = "2021"

[dependencies]
audiotags = "0.5.0"
clap = { version = "4.5.26", features = ["derive"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
sha2 = "0.10.8"
